Repository Marcelo-Diament/colearning-20220402, pull requests merged in 2022-04, with the labels that each got.

#1 doc: adicionando enunciados
  README.md
Labels: documentation

#5 feat/criando-pasta-modules-chamada-humanos
  modules/humanos.js
Labels: enhancement

#3 feat: Pasta data com arquivo pets.json e objetos criados!
  data/pets.json
Labels: enhancement, good first issue

#6 feat: Adicionando função ExibirPet
  modules/pets.js
Labels: enhancement

#2 feature: foi utilizado o comando npm init e ajustado
  package.json
Labels: enhancement, good first issue

#4 doc: criando arquivo js
  index.js
Labels: enhancement
